export const FILTER_PRODUCTS_BY_QUERY = "FILTER_PRODUCTS_BY_QUERY";
export const ADD_PRODUCTS_TO_CART = "ADD_PRODUCTS_TO_CART";
export const COUNT_PRICE_OF_PRODUCTS_ON_CART =
  "COUNT_PRICE_OF_PRODUCTS_ON_CART";
export const UPDATE_DETAILS_MOD = "UPDATE_DETAILS_MOD ";
export const UPDATE_CATEGORIES_STORE = "UPDATE_CATEGORIES_STORE";
export const UPDATE_SECTIONS_STORE = "UPDATE_SECTIONS_STORE";
