const FILTER_PRODUCTS_BY_QUERY = "FILTER_PRODUCTS_BY_QUERY";
const ADD_PRODUCTS_TO_CART = "ADD_PRODUCTS_TO_CART";
const COUNT_PRICE_OF_PRODUCTS_ON_CART = "COUNT_PRICE_OF_PRODUCTS_ON_CART";
const UPDATE_DETAILS_MOD = "UPDATE_DETAILS_MOD ";

export {
  FILTER_PRODUCTS_BY_QUERY,
  ADD_PRODUCTS_TO_CART,
  COUNT_PRICE_OF_PRODUCTS_ON_CART,
  UPDATE_DETAILS_MOD,
};
